/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CaptureControl {
  get isFinished(): boolean
  stop(): Promise<unknown>
  wait(): Promise<unknown>
}

export declare class DxgiDuplicationSession {
  constructor(options?: DxgiSessionOptions | undefined | null)
  get width(): number
  get height(): number
  get format(): DxgiDuplicationFormat
  get refreshRate(): Array<number>
  acquireNextFrame(timeoutMs?: number | undefined | null): Frame | null
  recreate(): void
  switchMonitor(monitorIndex: number): void
}

export declare class Frame {
  get buffer(): Buffer
  get width(): number
  get height(): number
  get rowPitch(): number
  get depthPitch(): number
  get timestamp(): number
  get colorFormat(): ColorFormat
  get dirtyRegions(): Array<DirtyRegion>
  crop(startX: number, startY: number, endX: number, endY: number): Frame
  encode(format: ImageFormat): Buffer
  saveAsImage(path: string, format?: ImageFormat | undefined | null): void
}

export declare class ImageEncoder {
  constructor(format: ImageFormat, pixelFormat: ImageEncoderPixelFormat)
  encode(buffer: Buffer, width: number, height: number): Buffer
}

export declare class ScreenCapture {
  constructor(options: CaptureOptions, onFrameArrived: (frame: Frame) => void, onClosed?: ((error: string | null) => void) | undefined | null)
  start(): CaptureControl
}

export declare class VideoEncoder {
  constructor(options: VideoEncoderOptions)
  sendFrame(frame: Frame): void
  sendFrameWithAudio(frame: Frame, audioBuffer: Buffer): void
  sendFrameBuffer(buffer: Buffer, timestamp: number): void
  sendAudioBuffer(buffer: Buffer, timestamp?: number | undefined | null): void
  finish(): Buffer | null
}

export declare const enum AudioCodec {
  Aac = 'aac',
  Ac3 = 'ac3',
  AacAdts = 'aacAdts',
  AacHdcp = 'aacHdcp',
  Ac3Spdif = 'ac3Spdif',
  Ac3Hdcp = 'ac3Hdcp',
  Adts = 'adts',
  Alac = 'alac',
  AmrNb = 'amrNb',
  AwrWb = 'awrWb',
  Dts = 'dts',
  Eac3 = 'eac3',
  Flac = 'flac',
  Float = 'float',
  Mp3 = 'mp3',
  Mpeg = 'mpeg',
  Opus = 'opus',
  Pcm = 'pcm',
  Wma8 = 'wma8',
  Wma9 = 'wma9',
  Vorbis = 'vorbis'
}

export interface AudioSettings {
  codec?: AudioCodec
  bitrate?: number
  channelCount?: number
  sampleRate?: number
  bitsPerSample?: number
  disabled?: boolean
}

export declare function captureApiSupport(): CaptureApiSupport

export interface CaptureApiSupport {
  graphicsCapture: boolean
  cursorSettings: boolean
  borderSettings: boolean
  secondaryWindows: boolean
  minimumUpdateInterval: boolean
  dirtyRegions: boolean
}

export interface CaptureOptions {
  monitorIndex?: number
  windowName?: string
  windowHandle?: number
  usePicker?: boolean
  cursorCapture?: boolean
  drawBorder?: boolean
  includeSecondaryWindows?: boolean
  minimumUpdateIntervalMs?: number
  dirtyRegions?: boolean
  colorFormat?: ColorFormat
}

export declare const enum ColorFormat {
  Rgba16F = 'rgba16F',
  Rgba8 = 'rgba8',
  Bgra8 = 'bgra8'
}

export declare const enum ContainerFormat {
  Asf = 'asf',
  Mp3 = 'mp3',
  Mpeg4 = 'mpeg4',
  Avi = 'avi',
  Mpeg2 = 'mpeg2',
  Wave = 'wave',
  AacAdts = 'aacAdts',
  Adts = 'adts',
  ThreeGp = 'threeGp',
  Amr = 'amr',
  Flac = 'flac'
}

export interface DirtyRegion {
  x: number
  y: number
  width: number
  height: number
}

export declare const enum DxgiDuplicationFormat {
  Rgba16F = 'rgba16F',
  Rgb10A2 = 'rgb10A2',
  Rgb10XrA2 = 'rgb10XrA2',
  Rgba8 = 'rgba8',
  Rgba8Srgb = 'rgba8Srgb',
  Bgra8 = 'bgra8',
  Bgra8Srgb = 'bgra8Srgb'
}

export interface DxgiSessionOptions {
  monitorIndex?: number
  supportedFormats?: Array<DxgiDuplicationFormat>
}

export declare function enumerateMonitors(): Array<MonitorInfo>

export declare function enumerateWindows(): Array<WindowInfo>

export declare function foregroundWindow(): WindowInfo

export declare const enum ImageEncoderPixelFormat {
  Rgb16F = 'rgb16F',
  Bgra8 = 'bgra8',
  Rgba8 = 'rgba8'
}

export declare const enum ImageFormat {
  Jpeg = 'jpeg',
  Png = 'png',
  Gif = 'gif',
  Tiff = 'tiff',
  Bmp = 'bmp',
  JpegXr = 'jpegXr'
}

export declare function isSupported(): boolean

export declare function monitorFromIndex(index: number): MonitorInfo

export interface MonitorInfo {
  index: number
  name: string
  deviceName: string
  deviceString: string
  width: number
  height: number
  refreshRate: number
  handle: number
}

export declare function primaryMonitor(): MonitorInfo

export interface Rect {
  left: number
  top: number
  right: number
  bottom: number
}

export declare const enum VideoCodec {
  Argb32 = 'argb32',
  Bgra8 = 'bgra8',
  D16 = 'd16',
  H263 = 'h263',
  H264 = 'h264',
  H264Es = 'h264Es',
  Hevc = 'hevc',
  HevcEs = 'hevcEs',
  Iyuv = 'iyuv',
  L8 = 'l8',
  L16 = 'l16',
  Mjpg = 'mjpg',
  Nv12 = 'nv12',
  Mpeg1 = 'mpeg1',
  Mpeg2 = 'mpeg2',
  Rgb24 = 'rgb24',
  Rgb32 = 'rgb32',
  Wmv3 = 'wmv3',
  Wvc1 = 'wvc1',
  Vp9 = 'vp9',
  Yuy2 = 'yuy2',
  Yv12 = 'yv12'
}

export interface VideoEncoderOptions {
  path?: string
  video: VideoSettings
  audio?: AudioSettings
  container?: ContainerFormat
}

export interface VideoSettings {
  width: number
  height: number
  codec?: VideoCodec
  bitrate?: number
  frameRate?: number
  pixelAspectRatioNumerator?: number
  pixelAspectRatioDenominator?: number
  disabled?: boolean
}

export declare function windowFromContainsName(title: string): WindowInfo

export declare function windowFromHandle(handle: number): WindowInfo

export declare function windowFromName(title: string): WindowInfo

export interface WindowInfo {
  title: string
  processId: number
  processName: string
  rect: Rect
  titleBarHeight: number
  width: number
  height: number
  isValid: boolean
  handle: number
  monitorIndex?: number
}
